trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: azurecli-shared-resources

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Development'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './initial_config.sh'
    arguments: '$(RESOURCE_GROUP_NAME) $(STORAGE_ACCOUNT_NAME) $(CONTAINER_NAME) $(REGION)'
  displayName: 'Create shared resources'
